platform :ios, '8.0'

pod 'BlocksKit', '~> 2.2.5'
pod 'AFNetworking', '< 2.6.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'ReactiveCocoa', '~> 2.3.1'
pod 'SDWebImage', '~>3.7'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'JSONModel', '~> 1.1.0'
